<?php

/**
 * @var Test\StoreReviews\Block\Index $block
 */
?>
<?php
if ($block->isLoggedIn()):?>
    <div>
        <div><?= __('It is important for us to know your opinion about our store') ?></div>
        <form name="store_reviews" method="POST" id="store_reviews">
            <label for="title">Title</label>
            <input type="text" name="title">
            <label for="review">Review</label>
            <input type="text" name="review">
            <label for="pros">Pros</label>
            <input type="text" name="pros">
            <label for="cons">Cons</label>
            <input type="text" name="cons">
            <input type="submit" id="sent_store_reviews" name="calculate-total-submit" value="Sent">
        </form>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Test_StoreReviews/js/reviews": {
            "url": "<?= $block->getUrl('reviews/customer/result') ?>"
            }
        }
    }
</script>
