<?php
/** @var $block Magento\Framework\View\Element\Template */
?>
<?php
$textMessage = 'Test Config from php';
?>
<div style="background-color: hotpink">
    <button id="btn_click_3" ><?= __('Click Js 3')?></button>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Test_Js/js/test3": {
            "message": "<?= $textMessage ?>"
            }

        }
    }
</script>
